In [1]:
a = [1.0, 2.0, 1.0]

In [1]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [5]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [6]:
points[0]

tensor(4.)

In [7]:
points[None]
points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points.shape

torch.Size([6])

In [17]:
img_t = torch.randn(3, 5, 5)  # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [18]:
batch_t = torch.randn(2, 3, 5, 5)  # shape [batch, channels, rows, columns]

In [19]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [22]:
unsqueeze_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueeze_weights)
batch_weights = (batch_t * unsqueeze_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, img_gray_weighted.shape, batch_gray_weighted.shape

(torch.Size([2, 3, 5, 5]), torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [28]:
# 名前付きテンソル
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=["channels"])
img_named = img_t.refine_names(..., "channels", "rows", "columns")
batch_named = batch_t.refine_names(..., "channels", "rows", "columns")
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [32]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [33]:
gray_named = (img_named * weights_aligned).sum("channels")
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [35]:
gray_named = (img_named[..., :3] * weights_named).sum("channels")

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

In [37]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

In [10]:
# dtypes
double_points = torch.ones((10, 2), dtype=torch.double)
short_pints = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_pints.dtype

torch.int16

In [12]:
double_points = torch.zeros((10, 2)).double()
short_points = torch.ones(10, 2).short()
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [13]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [16]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [20]:
points_storage = points.storage()
points_short[3]

tensor(0, dtype=torch.int16)

In [22]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_points = points[1]
second_points.storage_offset()

2

In [25]:
second_points.size()

torch.Size([2])

In [26]:
points.stride()

(2, 1)