In [3]:
import imageio
import torch

In [3]:
img_arr = imageio.imread("data/bobby.jpg")
img_arr.shape

/var/folders/n8/pv0qg3q13r1f_9lbfy75_8_r0000gn/T/ipykernel_3740/1850207428.py:1: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread("data/bobby.jpg")


(720, 1280, 3)

In [5]:
img = torch.from_numpy(img_arr)
out = img.permute(2, 0, 1)
out.shape

torch.Size([3, 720, 1280])

In [6]:
import os

batch_size = 3
batch = torch.zeros(batch_size, 3, 256, 256, dtype=torch.uint8)
filenames = [name for name in os.listdir("data/cat/") if os.path.splitext(name)[-1] == ".png"]
for i, filename in enumerate(filenames):
    img_arr = imageio.imread("data/cat/" + filename)
    img_t = torch.from_numpy(img_arr)
    img_t = img_t.permute(2, 0, 1)
    img_t = img_t[:3]
    batch[i] = img_t

/var/folders/n8/pv0qg3q13r1f_9lbfy75_8_r0000gn/T/ipykernel_3740/219099561.py:7: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  img_arr = imageio.imread("data/cat/" + filename)


In [8]:
# 画像の正規化
batch = batch.float()
batch /= 255.0
batch[0]

tensor([[[0.6235, 0.6118, 0.4980,  ..., 0.6000, 0.5961, 0.6275],
         [0.6941, 0.5373, 0.6588,  ..., 0.4824, 0.5451, 0.5529],
         [0.5098, 0.6235, 0.4314,  ..., 0.5255, 0.5725, 0.6549],
         ...,
         [0.4667, 0.5255, 0.5216,  ..., 0.5059, 0.4706, 0.4471],
         [0.5216, 0.5255, 0.4941,  ..., 0.4588, 0.4824, 0.4549],
         [0.5216, 0.4980, 0.4745,  ..., 0.4510, 0.4824, 0.4784]],

        [[0.5412, 0.5255, 0.4235,  ..., 0.5255, 0.5255, 0.5725],
         [0.6235, 0.4627, 0.5804,  ..., 0.4078, 0.4745, 0.4824],
         [0.4392, 0.5451, 0.3490,  ..., 0.4588, 0.5020, 0.5922],
         ...,
         [0.3843, 0.4275, 0.4314,  ..., 0.4588, 0.4235, 0.4039],
         [0.4314, 0.4314, 0.4118,  ..., 0.4157, 0.4392, 0.4118],
         [0.4314, 0.4039, 0.3961,  ..., 0.4039, 0.4314, 0.4353]],

        [[0.5020, 0.4745, 0.3765,  ..., 0.5098, 0.5137, 0.5686],
         [0.6039, 0.4275, 0.5294,  ..., 0.3961, 0.4627, 0.4706],
         [0.4039, 0.5137, 0.3098,  ..., 0.4353, 0.4863, 0.

In [17]:
n_channels = batch.shape[1]
for c in range(n_channels):
    mean = torch.mean(batch[:, c])
    std = torch.std(batch[:, c])
    batch[:, c] = (batch[:, c] - mean) / std

In [1]:
# 表形式データ
import csv
import numpy as np
wine_path = "data/winequality-white.csv"
wineq_numpy = np.loadtxt(wine_path, dtype=np.float32, delimiter=";", skiprows=1)
wineq_numpy

array([[ 7.  ,  0.27,  0.36, ...,  0.45,  8.8 ,  6.  ],
       [ 6.3 ,  0.3 ,  0.34, ...,  0.49,  9.5 ,  6.  ],
       [ 8.1 ,  0.28,  0.4 , ...,  0.44, 10.1 ,  6.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]], dtype=float32)

In [2]:
col_list = next(csv.reader(open(wine_path), delimiter=";"))
wineq_numpy.shape, col_list

((4898, 12),
 ['fixed acidity',
  'volatile acidity',
  'citric acid',
  'residual sugar',
  'chlorides',
  'free sulfur dioxide',
  'total sulfur dioxide',
  'density',
  'pH',
  'sulphates',
  'alcohol',
  'quality'])

In [4]:
wineq = torch.from_numpy(wineq_numpy)
wineq.shape, wineq.dtype

(torch.Size([4898, 12]), torch.float32)

In [6]:
data = wineq[:, :-1]
target = wineq[:, -1]
data, data.shape, target, target.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  3.0000,  0.4500,  8.8000],
         [ 6.3000,  0.3000,  0.3400,  ...,  3.3000,  0.4900,  9.5000],
         [ 8.1000,  0.2800,  0.4000,  ...,  3.2600,  0.4400, 10.1000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  2.9900,  0.4600,  9.4000],
         [ 5.5000,  0.2900,  0.3000,  ...,  3.3400,  0.3800, 12.8000],
         [ 6.0000,  0.2100,  0.3800,  ...,  3.2600,  0.3200, 11.8000]]),
 torch.Size([4898, 11]),
 tensor([6., 6., 6.,  ..., 6., 7., 6.]),
 torch.Size([4898]))

In [7]:
target = wineq[:, -1].long()
target

tensor([6, 6, 6,  ..., 6, 7, 6])

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [10]:
target_onehot = torch.zeros(target.shape[0], 10)
target_onehot.scatter_(1, target.unsqueeze(1), 1.0)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [11]:
data_mean = torch.mean(data, dim=0)
data_var = torch.var(data, dim=0)
data_norm = (data - data_mean) / torch.sqrt(data_var)
data_norm

tensor([[ 1.7208e-01, -8.1761e-02,  2.1326e-01,  ..., -1.2468e+00,
         -3.4915e-01, -1.3930e+00],
        [-6.5743e-01,  2.1587e-01,  4.7996e-02,  ...,  7.3995e-01,
          1.3422e-03, -8.2419e-01],
        [ 1.4756e+00,  1.7450e-02,  5.4378e-01,  ...,  4.7505e-01,
         -4.3677e-01, -3.3663e-01],
        ...,
        [-4.2043e-01, -3.7940e-01, -1.1915e+00,  ..., -1.3130e+00,
         -2.6153e-01, -9.0545e-01],
        [-1.6054e+00,  1.1666e-01, -2.8253e-01,  ...,  1.0049e+00,
         -9.6251e-01,  1.8574e+00],
        [-1.0129e+00, -6.7703e-01,  3.7852e-01,  ...,  4.7505e-01,
         -1.4882e+00,  1.0448e+00]])

In [13]:
bad_indexes = target <= 3
torch.sum(bad_indexes)

tensor(20)

In [18]:
bad_data = data[target <= 3]
mid_data = data[(target > 3) & (target < 7)]
good_data = data[target >= 7]
bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)

for i, args in enumerate(zip(col_list, bad_mean, mid_mean, good_mean)):
    print("{:2} {:20} {:6.2f} {:6.2f} {:6.2f}".format(i, *args))

 0 fixed acidity          7.60   6.89   6.73
 1 volatile acidity       0.33   0.28   0.27
 2 citric acid            0.34   0.34   0.33
 3 residual sugar         6.39   6.71   5.26
 4 chlorides              0.05   0.05   0.04
 5 free sulfur dioxide   53.33  35.42  34.55
 6 total sulfur dioxide 170.60 141.83 125.25
 7 density                0.99   0.99   0.99
 8 pH                     3.19   3.18   3.22
 9 sulphates              0.47   0.49   0.50
10 alcohol               10.34  10.26  11.42


In [19]:
total_sulfur_thre = 141.83
total_sulfur_data = data[:, 6]
predicted_index = total_sulfur_data < total_sulfur_thre
actual_index = target > 5

n_matched = torch.sum(predicted_index & actual_index).item()
n_predicted = torch.sum(predicted_index).item()
n_actual = torch.sum(actual_index).item()
n_matched, n_matched / n_predicted, n_matched / n_actual

(2018, 0.74000733406674, 0.6193984039287906)